### ISSUE TITLE
'az batch application package create' file upload failing

### ISSUE THREAD

**Issue by christophwille** [Azure/cli#38]
Failing action:  https://github.com/christophwille/azurebatch-playground/runs/2465121361?check_suite_focus=true
Source script: https://github.com/christophwille/azurebatch-playground/blob/main/.github/workflows/simple-cicd.yml

Using

```
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Batch Task App Package
        path: ${{ env.BATCH_APP_PACKAGE_PATH }}/batchtaskapp.zip
```

I can collect the file no problems, but the az/cli action fails me with 

```
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [Errno 2] No such file or directory: '/home/runner/work/azurebatch-playground/azurebatch-playground/.app/batchtaskapp.zip'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/batch/_exception_handler.py", line 30, in batch_exception_handler
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 807, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/batch/custom.py", line 228, in create_application_package
    _upload_package_blob(cmd.cli_ctx, package_file, result.storage_url)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/batch/custom.py", line 209, in _upload_package_blob
    file_path=package_file,
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 453, in create_blob_from_path
    count = path.getsize(file_path)
  File "/usr/local/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/azurebatch-playground/azurebatch-playground/.app/batchtaskapp.zip'
To open an issue, please run: 'az feedback'
```

So the file is there, but the az/cli action doesn't see it - or I am doing something wrong compared to upload?

**Comment by christophwille** [comment]
ok, I decided to go down the rabbit hole and tried a few variations, and I ended up with a winner:

https://github.com/christophwille/azurebatch-playground/runs/2465690411?check_suite_focus=true

The source file for the action is here https://github.com/christophwille/azurebatch-playground/blob/main/.github/workflows/simple-cicd%20multijob.yml - the thing that makes it work is the change in the `deploy` job from absolute path to relative path (I initially had absolute again, then switched to relative).

So, it looks like as if `az batch application package create --application-name` can't deal properly with absolute paths.

**Comment by t-dedah** [comment]
@christophwille As this issue is from az cli itself, should we close this issue now?

**Comment by christophwille** [comment]
Unless you can move it to az yes.
